version: '3.8'

services:
    # React App
    react:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: eclipse
        ports:
            - '3000:3000'
        volumes:
            - .:/eclipse

volumes:
    eclipse:
