version: '3.8'

services:
    # React App
    react:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: eclipse
        ports:
            - '3001:3001'
        volumes:
            - .:/eclipse
        environment:
            - PORT=3001

volumes:
    eclipse:
