name: Publish to npm nightly

on:
    push:
        branches:
            - nightly
    pull_request:
        branches:
            - nightly

jobs:
    publish:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Set Git user
              run: |
                  git config --global user.email ${{ secrets.GH_EMAIL }}
                  git config --global user.name ${{ secrets.GH_USER }}

            - name: Set up Node.js
              uses: actions/setup-node@v1
              with:
                  node-version: '18'
                  ref: nightly
                  registry-url: 'https://registry.npmjs.org'

            - name: Install dependencies & Build package
              run: yarn install && yarn build-package

            - name: Publish to npm nightly
              run: |
                  npm publish --tag=nightly
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

            - name: Create GitHub Release
              uses: softprops/action-gh-release@v1
              with:
                  files: ./components
                  token: ${{ secrets.GITHUB_TOKEN }}
