name: Publish Nightly to npm

on:
    push:
        branches:
            - nightly
    pull_request:
        branches:
            - nightly

jobs:
    publish:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: '20'
                  registry-url: 'https://registry.npmjs.org'

            - name: Set up Git
              run: |
                  git config --global user.email "${{ secrets.GH_EMAIL }}"
                  git config --global user.name "${{ secrets.GH_USER }}"
                  git config --global credential.helper "store --file=.git-credentials"
                  echo "https://${{ secrets.GITHUB_TOKEN }}@github.com" > .git-credentials

            - name: Install dependencies
              run: yarn

            - name: Clean build artifacts
              run: yarn clean

            - name: Version bump (prerelease)
              run: |
                  git add .
                  git commit -m "Bump version to $(node -p -e "require('./package.json').version")"
                  git push --follow-tags
                  yarn version --prerelease --preid=nightly --follow-tags

            - name: Publish to npm (nightly)
              run: yarn publish --tag nightly
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
